# Generated by Django 4.2.7 on 2023-12-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_blog_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
