# Generated by Django 4.2.7 on 2023-12-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_mainpage_remove_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='image',
            field=models.ImageField(upload_to='on_main'),
        ),
    ]
