# Generated by Django 5.0.1 on 2024-01-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0015_alter_blog_publish_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
